owner: xnaas
repo: status

sites:
  - name: Homepage
    url: https://xnaas.info

status-website:
  cname: status.xnaas.info
  logoUrl: https://xnaas.info/avatar.jpg
  name: xnaas-status
  introMessage: Status page for my self-hosted stuffs.
  navbar:
    - title: Status
      href: /
    - title: xnaas.info
      href: https://xnaas.info
  theme: dark
