owner: xnaas
repo: status

sites:
  - name: Homepage
    url: https://xnaas.info
  - name: Scrutiny
    url: https://drive-status.xnaas.info
    expectedStatusCodes:
      - 401
      - 403
    icon: https://raw.githubusercontent.com/AnalogJ/scrutiny/master/webapp/frontend/src/favicon.ico
  - name: thelounge
    url: https://irc.xnaas.info
  - name: KB
    url: https://kb.xnaas.info
  - name: Owncast
    url: https://live.xnaas.info
  - name: Music
    url: https://music.xnaas.info
    icon: https://raw.githubusercontent.com/navidrome/navidrome/master/resources/logo-192x192.png
  - name: Notes
    url: https://notes.xnaas.info
    icon: https://raw.githubusercontent.com/laurent22/joplin/dev/Assets/SquareIcon512.png
  - name: Plex
    url: https://plex.xnaas.info
    expectedStatusCodes:
      - 401
      - 403
    icon: https://www.plex.tv/wp-content/themes/plex/assets/img/favicons/favicon-16x16.png
  - name: PlexPy
    url: https://plexpy.xnaas.info
  - name: Overseerr
    url: https://request.xnaas.info
  - name: FreshRSS
    url: https://rss.xnaas.info
  - name: TeslaMate
    url: https://tesla.xnaas.info
    expectedStatusCodes:
      - 401
      - 403
    icon: https://raw.githubusercontent.com/adriankumpf/teslamate/master/assets/static/favicon-16x16.png
  - name: Grafana
    url: https://teslag.xnaas.info
    icon: https://raw.githubusercontent.com/adriankumpf/teslamate/master/assets/static/favicon-16x16.png

status-website:
  cname: status.xnaas.info
  logoUrl: https://xnaas.info/avatar.jpg
  favicon: https://xnaas.info/favicon.ico
  name: xnaas-status
  introMessage: Status page for my self-hosted stuffs.
  navbar:
    - title: Status
      href: /
    - title: xnaas.info
      href: https://xnaas.info
  theme: dark
